name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses:  benmatselby/hugo-deploy-gh-pages@main
      env:
        HUGO_VERSION: 0.105.0
        HUGO_EXTENDED: true
        GO_VERSION: 1.19.3
        TARGET_REPO: ThomasBrazier/thomasbrazier.github.io
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: www.thomasbrazier.github.io

